services:
  minio:
    image: minio/minio:latest
    container_name: edugate-minio
    restart: always
    ports:
      - "9000:9000"
      - "9002:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"

  minio-client:
    image: minio/mc
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
    entrypoint: >
      /bin/sh -c "
        echo 'Waiting for MinIO to start...';
        sleep 8;
        echo 'Connecting to MinIO...';
        mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
        echo 'Creating bucket: ${MINIO_BUCKET}...';
        mc mb myminio/${MINIO_BUCKET} || true;
        echo 'Setting bucket policy to public...';
        mc anonymous set download myminio/${MINIO_BUCKET};
        echo 'MinIO setup completed.';
        exit 0;
      "